[phases.setup]
nixPkgs = ["go"]

[phases.install]
cmds = [
  "go mod download",
  "go mod verify"
]

[phases.build]
cmds = [
  "go build -tags web -o main ./cmd/api"
]

[start]
cmd = "./main"

[variables]
CGO_ENABLED = "0"
GOOS = "linux"
GOARCH = "amd64"
